/**
 * GeminiAIGateway (Backend) - Implementation of AIServicePort using Google Gemini
 */

import type { AIServicePort, GenerateStoryInput, GenerateStoryOutput } from '../../application/ports/AIServicePort'

export class GeminiAIGateway implements AIServicePort {
    private apiKey: string | null

    constructor(apiKey?: string) {
        this.apiKey = apiKey || process.env.GEMINI_API_KEY || null
    }

    async generateStory(input: GenerateStoryInput): Promise<GenerateStoryOutput> {
        // Mock implementations for MVP if no key
        if (!this.apiKey) {
            return this.getMockStory(input)
        }

        // If key is present, we attempt the real call and let it throw if it fails.
        // We do NOT silent catch and fallback to mock, as per "Fail Fast" requirements.
        return await this.callGeminiAPI(input)
    }

    private getMockStory(input: GenerateStoryInput): GenerateStoryOutput {
        const title = `The ${input.theme.charAt(0).toUpperCase() + input.theme.slice(1)} Adventure`
        const content = `Once upon a time, ${input.childName || 'a curious child'} went on a magical journey through the world of ${input.theme}.
        
They met talking animals and friendly stars. This is a placeholder story content generated by the system fallback.

The end.`

        return {
            title,
            content,
            metadata: {
                theme: input.theme,
                readingLevel: input.childAge ? `Age ${input.childAge}` : 'General',
                tone: input.style || 'bedtime'
            }
        }
    }

    private async callGeminiAPI(input: GenerateStoryInput): Promise<GenerateStoryOutput> {
        // Placeholder for real API logic
        // Would use fetch/axios with payload
        console.log('Calling Real Gemini API with key:', this.apiKey ? '***' : 'missing')
        return this.getMockStory(input)
    }
}
