import { AIServicePort, GenerateStoryInput, GenerateStoryOutput, AgentThoughtInput, AgentThoughtOutput, LiveSessionOptions, LiveSessionPort } from '../../application/ports/AIServicePort.js'

export class MockAIService implements AIServicePort {
    async generateStory(input: GenerateStoryInput): Promise<GenerateStoryOutput> {
        // Simulate network latency (500ms - 1.5s)
        const delay = Math.random() * 1000 + 500
        await new Promise(resolve => setTimeout(resolve, delay))

        return {
            title: `Mock Story: ${input.theme}`,
            content: `This is a simulated AI story about ${input.theme}. It was generated by the MockAIService for testing purposes. Not real AI content.`,
            metadata: {
                theme: input.theme,
                readingLevel: 'General',
                tone: 'Mock'
            }
        }
    }

    async generateAgentThought(input: AgentThoughtInput): Promise<AgentThoughtOutput> {
        return {
            goals_considered: ['TESTING', 'MOCKING'],
            conflicts_identified: null,
            trade_off_made: null,
            thought: '[MOCK] Reasoning about ' + (input.userMessage || 'context'),
            reasoning: '[MOCK] Deprecated reasoning field',
            action: 'MOCK_ACTION',
            confidence: 0.99,
            parameters: { mocked: true }
        }
    }

    async *generateStoryStream(input: GenerateStoryInput): AsyncGenerator<string, void, unknown> {
        const words = `This is a simulated streaming story about ${input.theme}.`.split(' ')
        for (const word of words) {
            yield word + ' '
            await new Promise(resolve => setTimeout(resolve, 50))
        }
    }

    async startLiveSession(options?: LiveSessionOptions): Promise<LiveSessionPort> {
        return {
            sendAudio: () => { },
            sendText: () => { },
            onAudio: () => { },
            onText: () => { },
            onToolCall: () => { },
            onInterruption: () => { },
            onClose: () => { },
            onError: () => { },
            sendToolResponse: () => { },
            disconnect: () => { }
        }
    }

    async generateStructured<T = unknown>(input: { systemPrompt?: string, userMessage: string, schema: unknown }): Promise<T> {
        // Mock implementation for Ralph Loop
        if (input.systemPrompt && input.systemPrompt.includes("Memory Consolidator")) {
            return [
                {
                    fact: "Child loves mock dinosaurs",
                    confidence: 0.95,
                    lineReference: 1
                }
            ] as unknown as T
        }
        if (input.systemPrompt && input.systemPrompt.includes('Safety Validator')) {
            return { isSafe: true, reason: 'mock' } as unknown as T
        }
        return { mocked: true } as unknown as T
    }
}
